name: Trigger auto build for misaka-telegram-bot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      [ master ]
    paths:
      - '**'
      - '.github/workflows/ci.yml'

  # Allow manually trigger
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci

      - run: npm run build:js

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: misakakumomi/telegram-bot:${{ github.sha }}
          file: ./Dockerfile
          context: ./
