name: Trigger auto deployment for misaka-telegram-bot

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/misaka-telegram-bot-AutoDeployTrigger-de2533d6-3c64-4167-848b-41c70ee6d795.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ci

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: misakakumomi/telegram-bot:latest
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    environment: ci
    needs: build
    
    steps:
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n misaka-telegram-bot -g misaka-telegram-bot --server docker.io
            az containerapp update -n misaka-telegram-bot -g misaka-telegram-bot --image misakakumomi/telegram-bot:latest
